### ISSUE TITLE
Blink program doesn't terminate

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/Blink#43]
When running in the `-p -t` mode, it never closes.

**Comment by ssmirr** [comment]
@chrisparnin It's because the ticking sound track is 30 min not 25 min. So just need to crop the mp3 and it should work fine.

**Comment by ssmirr** [comment]
Not tested yet but It should be fixed now. Stops at 25:06.

**Comment by chrisparnin** [comment]
Program should terminate based on length.

A seperate issue: Make `-t` work when not doing `-p`, and scale to length, e.g., should be able to support 5 minutes or 50 minutes.

**Comment by ssmirr** [comment]
:white_check_mark: Will work on scaling.
